import { Archive, Copy, Download, FolderOpen, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../api";
import type { DashboardStatus, LogPage } from "../types";

function localDate(value: Date) { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; }
const taskLabels: Record<string, string> = { daily_send: "每日发送", health_check: "登录检查", login: "扫码登录", friend_scan: "好友识别", system: "系统" };
const statusLabels: Record<string, string> = { active: "当前", resolved: "已解决", historical: "历史" };

export function LogsPage({ summary }: { summary?: DashboardStatus["statistics"]["log_summary"] }) {
  const today = new Date(); const recent = new Date(today); recent.setDate(today.getDate() - 2);
  const [startDate, setStartDate] = useState(localDate(recent)); const [endDate, setEndDate] = useState(localDate(today));
  const [level, setLevel] = useState(""); const [taskType, setTaskType] = useState(""); const [status, setStatus] = useState("");
  const [logs, setLogs] = useState<LogPage | null>(null); const [tab, setTab] = useState<"scheduler" | "application">("application");
  const load = async () => setLogs(await api.logs({ start_date: startDate, end_date: endDate, level, task_type: taskType, status }));
  useEffect(() => { void load(); }, []);
  const archive = async () => { if (!window.confirm(`归档 ${startDate} 之前的应用日志？日志只会移动，不会删除。`)) return; const result = await api.archiveLogs(startDate); window.alert(`已归档 ${result.archived_count} 个日志文件。`); await load(); };
  const archiveHistorical = async () => { const result = await api.archiveHistoricalLogs(); window.alert(`已归档 ${result.archived_count} 个历史日志文件。`); await load(); };
  const copySummary = async () => { const active = logs?.items.filter((item) => item.status === "active" && item.level === "ERROR") || []; const text = active.map((item) => `${item.timestamp} ${item.summary}`).join("\n") || "当前没有活跃错误"; await navigator.clipboard?.writeText(text); window.alert("已复制精简错误摘要。"); };
  return <section className="editor-page"><header className="page-header"><div><h1>运行日志</h1><p>默认显示最近三天；追踪详情折叠显示，好友名称按设置脱敏。</p></div><div className="header-actions"><a className="action-button" href="/api/logs/diagnostic-export"><Download size={17} />导出脱敏诊断包</a><button className="action-button" onClick={() => void api.openLogFolder()}><FolderOpen size={17} />打开日志目录</button><button className="action-button" onClick={() => void archiveHistorical()}><Archive size={17} />归档历史日志</button><button className="action-button" onClick={() => void archive()}><Archive size={17} />按日期归档</button><button className="action-button" onClick={() => void copySummary()}><Copy size={17} />复制错误摘要</button><button className="action-button" onClick={() => void load()}><RefreshCw size={17} />刷新</button></div></header>
    {summary ? <div className="stats-grid log-stats"><article className="panel stat-card"><small>活跃错误</small><strong>{summary.active_errors}</strong></article><article className="panel stat-card"><small>24 小时警告</small><strong>{summary.warnings_24h}</strong></article><article className="panel stat-card"><small>7 天成功任务</small><strong>{summary.successful_tasks_7d}</strong></article><article className="panel stat-card"><small>最后错误</small><strong>{summary.last_error_time || "—"}</strong></article></div> : null}
    <div className="panel log-panel"><div className="tab-list"><button className={tab === "application" ? "active" : ""} onClick={() => setTab("application")}>应用日志</button><button className={tab === "scheduler" ? "active" : ""} onClick={() => setTab("scheduler")}>调度日志</button></div>{tab === "application" ? <><div className="log-filters"><label>开始日期<input aria-label="日志开始日期" type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label>结束日期<input aria-label="日志结束日期" type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label><label>级别<select aria-label="日志级别" value={level} onChange={(event) => setLevel(event.target.value)}><option value="">全部</option><option>INFO</option><option>WARNING</option><option>ERROR</option></select></label><label>任务<select aria-label="日志任务" value={taskType} onChange={(event) => setTaskType(event.target.value)}><option value="">全部</option>{Object.entries(taskLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>状态<select aria-label="日志状态" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部</option>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div><div className="structured-logs">{logs?.items.length ? logs.items.map((entry, index) => <article className={`log-entry ${entry.level.toLowerCase()}`} key={`${entry.fingerprint || entry.timestamp}-${index}`}><div className="log-summary"><time>{entry.timestamp}</time><span className={`tag ${entry.level === "ERROR" ? "failed" : entry.level === "WARNING" ? "warning" : "success"}`}>{entry.level}</span><span>{taskLabels[entry.task_type] || "系统"} · {statusLabels[entry.status] || "已解决"}</span><strong>{entry.summary}{entry.occurrences > 1 ? `（相同错误重复 ${entry.occurrences} 次）` : ""}</strong></div>{entry.detail ? <details><summary>查看详情</summary><pre>{entry.detail}</pre></details> : null}</article>) : <div className="empty-state compact">所选范围暂无日志</div>}</div></> : <pre>{logs?.scheduler || "暂无调度日志"}</pre>}</div></section>;
}
