import { Archive, Copy, Download, FolderOpen, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../api";
import type { DashboardStatus, LogPage } from "../types";

type StorageSummary = Awaited<ReturnType<typeof api.logStorageSummary>>;
type CleanupPreview = Awaited<ReturnType<typeof api.logCleanupPreview>>;

function localDate(value: Date) { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; }
function megabytes(value: number) { return `${(value / 1024 / 1024).toFixed(value ? 2 : 0)} MB`; }
const taskLabels: Record<string, string> = { daily_send: "每日发送", health_check: "登录检查", login: "扫码登录", friend_scan: "好友识别", system: "系统" };
const statusLabels: Record<string, string> = { active: "当前", resolved: "已解决", historical: "历史" };

export function LogsPage({ summary }: { summary?: DashboardStatus["statistics"]["log_summary"] }) {
  const today = new Date(); const recent = new Date(today); recent.setDate(today.getDate() - 2);
  const [startDate, setStartDate] = useState(localDate(recent)); const [endDate, setEndDate] = useState(localDate(today));
  const [level, setLevel] = useState(""); const [taskType, setTaskType] = useState(""); const [status, setStatus] = useState("");
  const [logs, setLogs] = useState<LogPage | null>(null); const [tab, setTab] = useState<"scheduler" | "application">("application");
  const [storage, setStorage] = useState<StorageSummary | null>(null); const [preview, setPreview] = useState<CleanupPreview | null>(null);
  const load = async () => setLogs(await api.logs({ start_date: startDate, end_date: endDate, level, task_type: taskType, status }));
  const loadStorage = async () => setStorage(await api.logStorageSummary());
  useEffect(() => { void load(); void loadStorage(); }, []);
  const archive = async () => { if (!window.confirm(`归档 ${startDate} 之前的应用日志？日志只会移动，不会删除。`)) return; const result = await api.archiveLogs(startDate); window.alert(`已归档 ${result.archived_count} 个日志文件。`); await Promise.all([load(), loadStorage()]); };
  const archiveHistorical = async () => { const result = await api.archiveHistoricalLogs(); window.alert(`已归档 ${result.archived_count} 个历史日志文件。`); await Promise.all([load(), loadStorage()]); };
  const copySummary = async () => { const active = logs?.items.filter((item) => item.status === "active" && item.level === "ERROR") || []; const text = active.map((item) => `${item.timestamp} ${item.summary}`).join("\n") || "当前没有活跃错误"; await navigator.clipboard?.writeText(text); window.alert("已复制精简错误摘要。"); };
  const openCleanupPreview = async () => setPreview(await api.logCleanupPreview());
  const confirmCleanup = async () => { const result = await api.cleanupLogs(); setPreview(null); window.alert(`已归档 ${result.archived} 个日志文件\n已删除 ${result.deleted} 个过期归档\n释放空间 ${megabytes(result.bytes)}\n跳过 ${result.skipped} 个文件`); await Promise.all([load(), loadStorage()]); };
  return <section className="editor-page"><header className="page-header"><div><h1>运行日志</h1><p>默认显示最近三天；追踪详情折叠显示，好友名称按设置脱敏。</p></div><div className="header-actions"><a className="action-button" href="/api/logs/diagnostic-export"><Download size={17} />导出脱敏诊断包</a><button className="action-button" onClick={() => void api.openLogFolder()}><FolderOpen size={17} />打开日志目录</button><button className="action-button" onClick={() => void archiveHistorical()}><Archive size={17} />归档历史日志</button><button className="action-button" onClick={() => void archive()}><Archive size={17} />按日期归档</button><button className="action-button primary" onClick={() => void openCleanupPreview()}>立即整理日志</button><button className="action-button" onClick={() => void copySummary()}><Copy size={17} />复制错误摘要</button><button className="action-button" onClick={() => void Promise.all([load(), loadStorage()])}><RefreshCw size={17} />刷新</button></div></header>
    {storage ? <div className="panel log-storage"><strong>日志存储</strong><span>活跃 {storage.active_files} 个 · {megabytes(storage.active_bytes)}</span><span>归档 {storage.archived_files} 个 · {megabytes(storage.archived_bytes)}</span><span>合计 {megabytes(storage.total_bytes)}</span><span>最早保留：{storage.oldest_date || "—"}</span><span>上次整理：{storage.last_cleanup_at || "尚未执行"}</span><span>下次自动整理：{storage.cleanup_enabled ? storage.next_cleanup_date : "已关闭"}</span></div> : null}
    {preview ? <div className="cleanup-dialog" role="dialog" aria-label="日志整理确认"><div className="panel"><h2>确认整理日志</h2><p>将归档 {preview.to_archive} 个活跃日志，删除 {preview.to_delete} 个过期归档；预计释放 {megabytes(preview.bytes)}，跳过 {preview.skipped} 个文件。</p><p>预览未修改任何文件。确认后仅处理 data/logs 及其 archive 目录中可识别的 AutoDy 日志。</p><div className="header-actions"><button className="action-button" onClick={() => setPreview(null)}>取消</button><button className="action-button primary" onClick={() => void confirmCleanup()}>确认整理</button></div></div></div> : null}
    {summary ? <div className="stats-grid log-stats"><article className="panel stat-card"><small>活跃错误</small><strong>{summary.active_errors}</strong></article><article className="panel stat-card"><small>24 小时警告</small><strong>{summary.warnings_24h}</strong></article><article className="panel stat-card"><small>7 天成功任务</small><strong>{summary.successful_tasks_7d}</strong></article><article className="panel stat-card"><small>最后错误</small><strong>{summary.last_error_time || "—"}</strong></article></div> : null}
    <div className="panel log-panel"><div className="tab-list"><button className={tab === "application" ? "active" : ""} onClick={() => setTab("application")}>应用日志</button><button className={tab === "scheduler" ? "active" : ""} onClick={() => setTab("scheduler")}>调度日志</button></div>{tab === "application" ? <><div className="log-filters"><label>开始日期<input aria-label="日志开始日期" type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label>结束日期<input aria-label="日志结束日期" type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label><label>级别<select aria-label="日志级别" value={level} onChange={(event) => setLevel(event.target.value)}><option value="">全部</option><option>INFO</option><option>WARNING</option><option>ERROR</option></select></label><label>任务<select aria-label="日志任务" value={taskType} onChange={(event) => setTaskType(event.target.value)}><option value="">全部</option>{Object.entries(taskLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>状态<select aria-label="日志状态" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部</option>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div><div className="structured-logs">{logs?.items.length ? logs.items.map((entry, index) => <article className={`log-entry ${entry.level.toLowerCase()}`} key={`${entry.fingerprint || entry.timestamp}-${index}`}><div className="log-summary"><time>{entry.timestamp}</time><span className={`tag ${entry.level === "ERROR" ? "failed" : entry.level === "WARNING" ? "warning" : "success"}`}>{entry.level}</span><span>{taskLabels[entry.task_type] || "系统"} · {statusLabels[entry.status] || "已解决"}</span><strong>{entry.summary}{entry.occurrences > 1 ? `（相同错误重复 ${entry.occurrences} 次）` : ""}</strong></div>{entry.detail ? <details><summary>查看详情</summary><pre>{entry.detail}</pre></details> : null}</article>) : <div className="empty-state compact">所选范围暂无日志</div>}</div></> : <pre>{logs?.scheduler || "暂无调度日志"}</pre>}</div></section>;
}
